### PR TITLE
fix lgpl v3.0 only url

### PR DESCRIPTION
**Pull request by zhfeng**
### Checklist:

* [ ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/bacon/wiki/Changelog) for your change if user-facing?
* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Review by svkcemk — APPROVED** [review]

**Comment by saumya1singh** [comment]
LGTM

**Comment by zhfeng** [comment]
sorry I need to change `jboss-parent`

**Comment by zhfeng** [comment]
OK, it is good now.

**Comment by zhfeng** [comment]
Oh, sorry, `jboss-parent` is still wrong. The version >= 40 should be `Apache License`

**Pull request merged**
